server:
  port: 8085

  
spring:
 application:
    name: Currency-Rate-Convertion-Service
 zipkin:
    base-url: http://192.168.99.100:9411/
    
 sleuth:
    sampler:
      probability: 1.0
    trace-id128: true   
    

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka    
      
msg: prod conversion production- Hello world    

rate.converstion.service.uri: https://api.exchangeratesapi.io/latest    
